Repository software-students-fall2021/project-setup-potluck, pull requests merged in 2021-11, with the labels that each got.

#62 Implement geolocation feature + Map restaurants with the backend
  back-end/app.js
  back-end/routes/restaurants.js
  front-end/src/components/Map.js
  front-end/src/components/RestaurantPage.js
Labels: Ready for Review

#66 Make restaurants clickable map
  .gitignore
  back-end/routes/restaurants.js
  front-end/src/App.js
  front-end/src/components/Map.js
  front-end/src/components/RestaurantFeed.js
  front-end/src/components/RestaurantPage.js
Labels: Ready for Review

#63 GET: /Search route successfully implemented
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/searchRoute.js
Labels: Ready for Review

#64 SearchBar Get Request from server/mockaroo integration
  front-end/src/components/Header.js
Labels: Ready for Review

#65 modified RestaurantPage
  back-end/routes/restaurants.js
  front-end/src/components/BiggerContainer.js
  front-end/src/components/FoodContainer2x2.js
  front-end/src/components/RestaurantPage.js
  front-end/src/styles/BiggerContainer.css
  front-end/src/styles/FoodContainer2x2.css
  front-end/src/styles/RestaurantPage.css
Labels: help wanted, Ready for Review

#70 Configured unit tests/coverage, wrote search route tests
  back-end/.babelrc
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/tests/test.js
Labels: Ready for Review

#67 Call restaurant data mockaroo
  back-end/routes/restaurants.js
  front-end/src/App.js
  front-end/src/components/Map.js
  front-end/src/components/RestaurantPage.js
Labels: Ready for Review

#79 integrated MyAccountPage.js (front) with userRoute.js (back)
  back-end/app.js
  back-end/routes/usernameRoute.js
  back-end/tests/test.js
  front-end/src/App.js
  package-lock.json
Labels: help wanted, Ready for Review

#82 forgot to push MyAccountPage.js and .css - apolgoies
  front-end/src/components/MyAccountPage.js
  front-end/src/styles/MyAccountPage.css
Labels: Ready for Review

#83 userRoute.js was never pushed along with all other files for some rea…
  back-end/routes/userRoute.js
Labels: Ready for Review

#84 changed name of a component from GetData to MyAccountPage - more stra…
  front-end/src/App.js
  front-end/src/components/MyAccountPage.js
Labels: Ready for Review

#106 Add basic DB connection script and sample MongoDB model
  back-end/app.js
  back-end/models/exampleModel.js
Labels: Ready for Review

#114 completed Post schema as well as first version of search retrieval fr…
  back-end/models/postModel.js
  back-end/routes/searchRoute.js
Labels: Ready for Review

#115 Integrate restaurant mongodb backend
  .gitignore
  back-end/app.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/loginRoute.js
  back-end/routes/registerRoute.js
  back-end/routes/restaurants.js
  back-end/routes/restaurantsRoute.js
  back-end/server.js
  front-end/src/App.js
  front-end/src/components/Login.js
  front-end/src/components/Map.js
  front-end/src/components/MyAccountPage.js
  front-end/src/components/Register.js
Labels: Task

#118 Fixing something that got rolled back somehow
  back-end/models/postModel.js
  back-end/package.json
Labels: Ready for Review

#120 Working Retrieve posts from database
  back-end/app.js
  back-end/models/postModel.js
  back-end/models/userModel.js
  back-end/package-lock.json
  back-end/routes/searchRoute.js
  back-end/server.js
  front-end/src/components/FeedPage.js
  images/helloImage!.jpg
Labels: Ready for Review, Task
