Repository software-students-fall2021/project-setup-potluck, pull requests merged in 2021-12, with the labels that each got.

#119 Backend posting feed
  back-end/app.js
  back-end/models/postModel.js
  back-end/models/postingfeedModel.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/postFeedRoute.js
  back-end/routes/searchRoute.js
  back-end/server.js
  front-end/src/components/FeedPage.js
  front-end/src/components/PostFeed.js
  uploads/images_1638326643495.jpg
  uploads/images_1638326891664.png
  uploads/images_1638326968816.png
  uploads/images_1638326982020.png
  uploads/images_1638327056653.png
  uploads/images_1638327142768.png
  uploads/images_1638327179089.png
  uploads/images_1638327464229.jpeg
  uploads/images_1638333559240.jpg
  uploads/images_1638334283200.jpg
  uploads/images_1638334311041.jpg
  uploads/images_1638334360785.jpg
  uploads/images_1638334432360.jpg
  uploads/images_1638334454586.jpg
  uploads/images_1638334505913.jpg
  uploads/images_1638334520439.jpg
  uploads/images_1638334533587.jpg
  uploads/images_1638334631246.jpg
  uploads/images_1638334650705.jpg
  uploads/images_1638334748325.jpg
  uploads/images_1638334757569.jpg
  uploads/images_1638334774990.jpg
  uploads/images_1638334826206.jpg
  uploads/images_1638334942662.jpg
  uploads/images_1638335033912.jpg
  uploads/images_1638335044504.jpg
Labels: Ready to merge, user story

#122 [WIP] Fixing RestaurantPage
  back-end/package-lock.json
  back-end/package.json
  back-end/tests/test.js
  front-end/src/App.js
  front-end/src/components/Map.js
  front-end/src/components/RestaurantPage.js
Labels: Ready for Review

#133 [WIP] Merge tests
  README.md
  back-end/routes/loginRoute.js
  back-end/tests/test.js
  front-end/package.json
Labels: Ready for Review

#134 Change imports to require
  back-end/package-lock.json
  back-end/routes/loginRoute.js
  back-end/routes/logoutRoute.js
  back-end/routes/registerRoute.js
Labels: Ready to merge

#141 about us changes
  front-end/public/team/christian.jpg
  front-end/src/components/About.js
Labels: Ready for Review
